[theme]

# Primary accent color for interactive elements.
primaryColor = "#3c9df3"

# Background color for the main content area.
backgroundColor = "#f0f0f0"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#ffffff"

# Color used for almost all text.
textColor = "#525252"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
font = "sans serif"

[server]
runOnSave = true